dependencies:
  - name: postgresql
    version: 0.0.1
    repository: https://hanahmily.github.io/aliyun-chart/
  - name: redis
    version: 0.0.1
    repository: https://hanahmily.github.io/aliyun-chart/
