dependencies:
  - name: postgresql-aliyun
    version: 0.0.1
    repository: https://hanahmily.github.io/aliyun-chart/
  - name: redis-aliyun
    version: 0.0.1
    repository: https://hanahmily.github.io/aliyun-chart/
